import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import Footer from './component/footer'
import Header from './component/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {

  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
     
        {/* <h1>Main Layout</h1> */}
        {children}
        <Footer/>
       
        
      </body>
    </html>
  )
}